'use strict';

// Exporter — converts the pixel canvas to pxAt() code (mirrors png2sprite.js logic)

var Exporter = (function() {

    function generate(funcName, useLoff) {
        var W       = PixelCanvas.getWidth();
        var H       = PixelCanvas.getHeight();
        var pixels  = PixelCanvas.getPixels();
        var visited = new Uint8Array(W * H);
        var rects   = [];

        function toHex(r, g, b) {
            return '#' +
                ('0' + r.toString(16)).slice(-2).toUpperCase() +
                ('0' + g.toString(16)).slice(-2).toUpperCase() +
                ('0' + b.toString(16)).slice(-2).toUpperCase();
        }

        function getHex(x, y) {
            if (x < 0 || y < 0 || x >= W || y >= H) return null;
            var i = (y * W + x) * 4;
            if (pixels[i + 3] < 128) return null;
            return toHex(pixels[i], pixels[i + 1], pixels[i + 2]);
        }

        // Greedy rectangle scan (same algorithm as png2sprite.js)
        for (var ry = 0; ry < H; ry++) {
            for (var rx = 0; rx < W; rx++) {
                if (visited[ry * W + rx]) continue;
                var color = getHex(rx, ry);
                if (!color) { visited[ry * W + rx] = 1; continue; }

                var rw = 1;
                while (rx + rw < W && !visited[ry * W + rx + rw] && getHex(rx + rw, ry) === color) rw++;

                var rh = 1;
                outer: while (ry + rh < H) {
                    for (var dx = 0; dx < rw; dx++) {
                        if (visited[(ry + rh) * W + rx + dx] || getHex(rx + dx, ry + rh) !== color) break outer;
                    }
                    rh++;
                }

                rects.push({ x: rx, y: ry, w: rw, h: rh, color: color });

                for (var dy = 0; dy < rh; dy++)
                    for (var dx2 = 0; dx2 < rw; dx2++)
                        visited[(ry + dy) * W + (rx + dx2)] = 1;
            }
        }

        function pad(n, w) { var s = String(n); while (s.length < w) s = ' ' + s; return s; }
        var maxX = 0, maxY = 0, maxW = 0, maxH = 0;
        rects.forEach(function(r) {
            if (r.x > maxX) maxX = r.x;
            if (r.y > maxY) maxY = r.y;
            if (r.w > maxW) maxW = r.w;
            if (r.h > maxH) maxH = r.h;
        });
        var xW = String(maxX).length, yW = String(maxY).length;
        var wW = String(maxW).length, hW = String(maxH).length;

        var sig = useLoff
            ? 'function ' + funcName + '(ctx, bx, by, lOff) {'
            : 'function ' + funcName + '(ctx, bx, by) {';

        var lines = [];
        lines.push('// Generated by Pixel Art Tool  (' + W + '×' + H + ' px, ' + rects.length + ' rects)');
        lines.push('// Paste into js/sprites/sprites.js replacing the matching function');
        lines.push(sig);
        rects.forEach(function(r) {
            lines.push('    pxAt(ctx, bx, by, ' +
                pad(r.x, xW) + ', ' + pad(r.y, yW) + ', \'' + r.color + '\', ' +
                pad(r.w, wW) + ', ' + pad(r.h, hW) + ');');
        });
        lines.push('}');
        return lines.join('\n');
    }

    return { generate };
})();
