'use strict';

// Exporter — converts pixel data to pxAt() code (mirrors png2sprite.js logic)
// Supports single-frame (Sprite mode) and multi-frame (Animation mode) export.

var Exporter = (function() {

    function _toHex(r, g, b) {
        return '#' +
            ('0' + r.toString(16)).slice(-2).toUpperCase() +
            ('0' + g.toString(16)).slice(-2).toUpperCase() +
            ('0' + b.toString(16)).slice(-2).toUpperCase();
    }

    // Core: generate pxAt() code from a raw pixel array.
    // Used by both generate() (single frame) and generateMultiFrame().
    function _generateFromPixels(funcName, useLoff, pixels, W, H) {
        var visited = new Uint8Array(W * H);
        var rects   = [];

        function getHex(x, y) {
            if (x < 0 || y < 0 || x >= W || y >= H) return null;
            var i = (y * W + x) * 4;
            if (pixels[i + 3] < 128) return null;
            return _toHex(pixels[i], pixels[i + 1], pixels[i + 2]);
        }

        // Greedy rectangle scan (same algorithm as png2sprite.js)
        for (var ry = 0; ry < H; ry++) {
            for (var rx = 0; rx < W; rx++) {
                if (visited[ry * W + rx]) continue;
                var color = getHex(rx, ry);
                if (!color) { visited[ry * W + rx] = 1; continue; }

                var rw = 1;
                while (rx + rw < W && !visited[ry * W + rx + rw] && getHex(rx + rw, ry) === color) rw++;

                var rh = 1;
                outer: while (ry + rh < H) {
                    for (var dx = 0; dx < rw; dx++) {
                        if (visited[(ry + rh) * W + rx + dx] || getHex(rx + dx, ry + rh) !== color) break outer;
                    }
                    rh++;
                }

                rects.push({ x: rx, y: ry, w: rw, h: rh, color: color });

                for (var dy = 0; dy < rh; dy++)
                    for (var dx2 = 0; dx2 < rw; dx2++)
                        visited[(ry + dy) * W + (rx + dx2)] = 1;
            }
        }

        function pad(n, w) { var s = String(n); while (s.length < w) s = ' ' + s; return s; }
        var maxX = 0, maxY = 0, maxW = 0, maxH = 0;
        rects.forEach(function(r) {
            if (r.x > maxX) maxX = r.x;
            if (r.y > maxY) maxY = r.y;
            if (r.w > maxW) maxW = r.w;
            if (r.h > maxH) maxH = r.h;
        });
        var xW = String(maxX).length, yW = String(maxY).length;
        var wW = String(maxW).length, hW = String(maxH).length;

        var sig = useLoff
            ? 'function ' + funcName + '(ctx, bx, by, lOff) {'
            : 'function ' + funcName + '(ctx, bx, by) {';

        var lines = [];
        lines.push('// Generated by Pixel Art Tool  (' + W + '\u00D7' + H + ' px, ' + rects.length + ' rects)');
        lines.push('// Paste into js/sprites/sprites.js replacing the matching function');
        lines.push(sig);
        rects.forEach(function(r) {
            lines.push('    pxAt(ctx, bx, by, ' +
                pad(r.x, xW) + ', ' + pad(r.y, yW) + ', \'' + r.color + '\', ' +
                pad(r.w, wW) + ', ' + pad(r.h, hW) + ');');
        });
        lines.push('}');
        return lines.join('\n');
    }

    // Single-frame export (Sprite mode) — reads from PixelCanvas directly.
    function generate(funcName, useLoff) {
        return _generateFromPixels(
            funcName, useLoff,
            PixelCanvas.getPixels(), PixelCanvas.getWidth(), PixelCanvas.getHeight()
        );
    }

    // Multi-frame export (Animation mode).
    // frames: array of Uint8ClampedArray pixel arrays (one per frame)
    // 1 frame  → single function, base name only (no _f0 suffix) — Viktor V9
    // N frames → baseName_f0, _f1, ... with // Frame N headers
    function generateMultiFrame(baseName, useLoff, frames, w, h) {
        if (!frames.length) return '';
        if (frames.length === 1) {
            return _generateFromPixels(baseName, useLoff, frames[0], w, h);
        }
        var sections = [];
        for (var i = 0; i < frames.length; i++) {
            var funcName = baseName + '_f' + i;
            sections.push('// Frame ' + i);
            sections.push(_generateFromPixels(funcName, useLoff, frames[i], w, h));
        }
        return sections.join('\n\n');
    }

    // Spritesheet: composite all frames into a horizontal strip, return base64 PNG.
    function toSpritesheetBase64(frames, w, h) {
        if (!frames.length) return '';
        var totalW = w * frames.length;
        var offscreen = document.createElement('canvas');
        offscreen.width  = totalW;
        offscreen.height = h;
        var ctx = offscreen.getContext('2d');

        for (var f = 0; f < frames.length; f++) {
            var imgData = new ImageData(new Uint8ClampedArray(frames[f]), w, h);
            ctx.putImageData(imgData, f * w, 0);
        }

        return offscreen.toDataURL('image/png').split(',')[1];
    }

    return { generate, generateMultiFrame, toSpritesheetBase64 };
})();
