'use strict';

// tests/animation-export.test.js
// Tests for multi-frame pxAt() export and spritesheet compositing.
//
// Algorithm-extraction pattern: reimplements the export logic as standalone
// functions (same approach as exporter.test.js). Does NOT import the IIFE module.

// ── Extracted helpers ────────────────────────────────────────────────────────

function toHex(r, g, b) {
    return '#' +
        ('0' + r.toString(16)).slice(-2).toUpperCase() +
        ('0' + g.toString(16)).slice(-2).toUpperCase() +
        ('0' + b.toString(16)).slice(-2).toUpperCase();
}

function greedyRects(pixels, w, h) {
    var visited = new Uint8Array(w * h);
    var rects   = [];

    function getHex(x, y) {
        if (x < 0 || y < 0 || x >= w || y >= h) return null;
        var i = (y * w + x) * 4;
        if (pixels[i + 3] < 128) return null;
        return toHex(pixels[i], pixels[i + 1], pixels[i + 2]);
    }

    for (var ry = 0; ry < h; ry++) {
        for (var rx = 0; rx < w; rx++) {
            if (visited[ry * w + rx]) continue;
            var color = getHex(rx, ry);
            if (!color) { visited[ry * w + rx] = 1; continue; }

            var rw = 1;
            while (rx + rw < w && !visited[ry * w + rx + rw] && getHex(rx + rw, ry) === color) rw++;

            var rh = 1;
            outer: while (ry + rh < h) {
                for (var dx = 0; dx < rw; dx++) {
                    if (visited[(ry + rh) * w + rx + dx] || getHex(rx + dx, ry + rh) !== color) break outer;
                }
                rh++;
            }

            rects.push({ x: rx, y: ry, w: rw, h: rh, color: color });

            for (var dy = 0; dy < rh; dy++)
                for (var dx2 = 0; dx2 < rw; dx2++)
                    visited[(ry + dy) * w + (rx + dx2)] = 1;
        }
    }
    return rects;
}

// Mirrors Exporter._generateFromPixels
function generateFromPixels(funcName, useLoff, pixels, W, H) {
    var rects = greedyRects(pixels, W, H);

    function pad(n, w) { var s = String(n); while (s.length < w) s = ' ' + s; return s; }
    var maxX = 0, maxY = 0, maxW = 0, maxH = 0;
    rects.forEach(function(r) {
        if (r.x > maxX) maxX = r.x;
        if (r.y > maxY) maxY = r.y;
        if (r.w > maxW) maxW = r.w;
        if (r.h > maxH) maxH = r.h;
    });
    var xW = String(maxX).length, yW = String(maxY).length;
    var wW = String(maxW).length, hW = String(maxH).length;

    var sig = useLoff
        ? 'function ' + funcName + '(ctx, bx, by, lOff) {'
        : 'function ' + funcName + '(ctx, bx, by) {';

    var lines = [];
    lines.push('// Generated by Pixel Art Tool  (' + W + '\u00D7' + H + ' px, ' + rects.length + ' rects)');
    lines.push('// Paste into js/sprites/sprites.js replacing the matching function');
    lines.push(sig);
    rects.forEach(function(r) {
        lines.push('    pxAt(ctx, bx, by, ' +
            pad(r.x, xW) + ', ' + pad(r.y, yW) + ', \'' + r.color + '\', ' +
            pad(r.w, wW) + ', ' + pad(r.h, hW) + ');');
    });
    lines.push('}');
    return lines.join('\n');
}

// Mirrors Exporter.generateMultiFrame
function generateMultiFrame(baseName, useLoff, frames, w, h) {
    if (frames.length === 1) {
        return generateFromPixels(baseName, useLoff, frames[0], w, h);
    }
    var sections = [];
    for (var i = 0; i < frames.length; i++) {
        var funcName = baseName + '_f' + i;
        sections.push('// Frame ' + i);
        sections.push(generateFromPixels(funcName, useLoff, frames[i], w, h));
    }
    return sections.join('\n\n');
}

// Build a flat RGBA pixel array from a 2D grid of hex strings (null = transparent)
function makePixels(colorGrid) {
    var h = colorGrid.length;
    var w = colorGrid[0].length;
    var pixels = new Uint8ClampedArray(w * h * 4);
    for (var y = 0; y < h; y++) {
        for (var x = 0; x < w; x++) {
            var hex = colorGrid[y][x];
            if (!hex) continue;
            var i = (y * w + x) * 4;
            pixels[i]     = parseInt(hex.slice(1, 3), 16);
            pixels[i + 1] = parseInt(hex.slice(3, 5), 16);
            pixels[i + 2] = parseInt(hex.slice(5, 7), 16);
            pixels[i + 3] = 255;
        }
    }
    return { pixels: pixels, w: w, h: h };
}

// ── Tests ─────────────────────────────────────────────────────────────────────

describe('Multi-frame export — generateMultiFrame()', function() {

    test('2-frame animation: produces two functions with _f0 and _f1 suffixes', function() {
        var f0 = makePixels([['#FF0000']]);
        var f1 = makePixels([['#00FF00']]);
        var code = generateMultiFrame('walk', false, [f0.pixels, f1.pixels], 1, 1);

        expect(code).toContain('// Frame 0');
        expect(code).toContain('// Frame 1');
        expect(code).toContain('function walk_f0(ctx, bx, by)');
        expect(code).toContain('function walk_f1(ctx, bx, by)');
    });

    test('1-frame animation: single function, no _f0 suffix (Viktor V9)', function() {
        var f0 = makePixels([['#FF0000']]);
        var code = generateMultiFrame('idle', false, [f0.pixels], 1, 1);

        expect(code).toContain('function idle(ctx, bx, by)');
        expect(code).not.toContain('idle_f0');
        expect(code).not.toContain('// Frame 0');
    });

    test('3-frame animation: correct naming sequence _f0, _f1, _f2', function() {
        var f = makePixels([['#AABBCC']]);
        var code = generateMultiFrame('run', false, [f.pixels, f.pixels, f.pixels], 1, 1);

        expect(code).toContain('function run_f0(');
        expect(code).toContain('function run_f1(');
        expect(code).toContain('function run_f2(');
        expect(code).not.toContain('function run(ctx');
    });

    test('each frame produces correct pxAt rects for its own pixel data', function() {
        var f0 = makePixels([['#FF0000', '#FF0000']]);  // 1 rect
        var f1 = makePixels([['#00FF00', '#0000FF']]);  // 2 rects
        var code = generateMultiFrame('test', false, [f0.pixels, f1.pixels], 2, 1);

        // Frame 0: single red rect 2×1
        var frame0Section = code.split('// Frame 1')[0];
        expect((frame0Section.match(/pxAt\(/g) || []).length).toBe(1);

        // Frame 1: two rects (green + blue)
        var frame1Section = code.split('// Frame 1')[1];
        expect((frame1Section.match(/pxAt\(/g) || []).length).toBe(2);
    });

    test('lOff parameter propagates to all frames', function() {
        var f = makePixels([['#FF0000']]);
        var code = generateMultiFrame('walk', true, [f.pixels, f.pixels], 1, 1);

        expect(code).toContain('function walk_f0(ctx, bx, by, lOff)');
        expect(code).toContain('function walk_f1(ctx, bx, by, lOff)');
    });

    test('empty frame (all transparent) produces function with no pxAt calls', function() {
        var f0 = makePixels([
            ['#FF0000', '#FF0000'],
            ['#FF0000', '#FF0000']
        ]);
        var blank = new Uint8ClampedArray(2 * 2 * 4); // 2×2 all zeros
        var code = generateMultiFrame('test', false, [f0.pixels, blank], 2, 2);

        // Frame 1 should have a function but no pxAt calls
        var frame1Section = code.split('// Frame 1')[1];
        expect(frame1Section).toContain('function test_f1(');
        expect(frame1Section).not.toContain('pxAt(');
    });

    test('dimension header matches supplied w×h, not pixel array length', function() {
        var f = makePixels([
            ['#FF0000', '#FF0000'],
            ['#FF0000', '#FF0000']
        ]);
        var code = generateMultiFrame('sprite', false, [f.pixels], 2, 2);

        expect(code).toContain('2\u00D72 px');
    });
});

describe('Spritesheet compositing logic', function() {

    test('horizontal strip: total width = frameWidth × frameCount', function() {
        // Verify pixel layout: frame 0 red, frame 1 blue, 1×1 each
        var f0 = makePixels([['#FF0000']]);
        var f1 = makePixels([['#0000FF']]);

        // Simulate what toSpritesheetBase64 does internally:
        // compose frames into a single pixel buffer horizontally
        var frames = [f0.pixels, f1.pixels];
        var w = 1, h = 1;
        var totalW = w * frames.length;
        var composed = new Uint8ClampedArray(totalW * h * 4);

        for (var f = 0; f < frames.length; f++) {
            for (var y = 0; y < h; y++) {
                for (var x = 0; x < w; x++) {
                    var srcIdx = (y * w + x) * 4;
                    var dstIdx = (y * totalW + (f * w + x)) * 4;
                    composed[dstIdx]     = frames[f][srcIdx];
                    composed[dstIdx + 1] = frames[f][srcIdx + 1];
                    composed[dstIdx + 2] = frames[f][srcIdx + 2];
                    composed[dstIdx + 3] = frames[f][srcIdx + 3];
                }
            }
        }

        // Pixel 0: red
        expect(composed[0]).toBe(255);   // R
        expect(composed[1]).toBe(0);     // G
        expect(composed[2]).toBe(0);     // B
        expect(composed[3]).toBe(255);   // A

        // Pixel 1: blue
        expect(composed[4]).toBe(0);     // R
        expect(composed[5]).toBe(0);     // G
        expect(composed[6]).toBe(255);   // B
        expect(composed[7]).toBe(255);   // A
    });

    test('spritesheet dimensions: 3 frames of 4×4 → 12×4 strip', function() {
        var w = 4, h = 4, frameCount = 3;
        var totalW = w * frameCount;

        expect(totalW).toBe(12);
        // Height unchanged
        expect(h).toBe(4);
    });

    test('single frame spritesheet: same as single PNG', function() {
        var f0 = makePixels([['#FF0000', '#00FF00']]);
        var frames = [f0.pixels];
        var w = 2, h = 1;
        var totalW = w * frames.length;

        expect(totalW).toBe(2); // no extra width
    });
});
